// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urfrlieqggopmwncwuwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZnJsaWVxZ2dvcG13bmN3dXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNTI0OTYsImV4cCI6MjA2NjcyODQ5Nn0.hQKnLjwc0iKmL2BMsSOuTJwrrgjRx69z9pbM_YB0oio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);